blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users import views


handler404 = "post.views.handler404"
handler500 = "post.views.handler500"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include("users.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include("post.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/post/urls.py
from django.contrib import admin
from django.urls import path

from . import views
# from .views import editBlog


urlpatterns = [
    #path('', views.classListView.as_view()),
    path('', views.home, name = "posts-home" ),
    # path('login/', views.register, name = "login" ),
    path('posts/', views.enlist_post, name = "post-list" ),
    path('404/', views.handler404, name = "post-404" ),
    path('500/', views.handler500, name = "post-500" ),
    path('create/', views.create_post, name = "create-post" ),
    path('contact/', views.contactAdmin, name = "contact-admin" ),
    path('about/', views.aboutUs, name = "about-us" ),
    path('like/<int:id>/', views.like, name = "post-like" ),
    path('view/<slug:slug>', views.view_post, name = "post-detail" ),
    path('delete/<slug:slug>', views.delete_post, name = "delete-post" ),
    path('view/<slug:slug>/edit/', views.update_post, name = "edit-post" ),
    path('blogRequest/<slug:slug>/', views.blogRequest, name = "blog-request" ),
    path('authorProfile/<int:id>/', views.authorProfile, name = "author-profile" ),
    # path('edit2/<int:pk>', views.editBlog.as_view(), name = "edit-post" ),
]

blog/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'users'


urlpatterns = [
    path('register/', views.register,name='register' ),
    path('user_login/', views.user_login,name='user_login' ),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'), 
    path('managePosts/', views.managePosts, name='manage-posts'),
    path('logout/', views.logmeout, name='log-out'),
    path('beblogger/', views.makeBloggers, name='make-bloggers'),
    path('profile/', views.userProfile, name='user-profile'),
    path('profile-edit/', views.edit_profile, name='user-profile-edit'),
    path('', views.adminHome, name='admin-home'),
    
]

blog/post/models.py
from __future__ import  unicode_literals
from django.db import models
from django.urls import reverse
from cloudinary.models import CloudinaryField
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.conf import settings
from time import gmtime, strftime
from django.http import request
from django.utils import timezone
from django.contrib.contenttypes.models import ContentType

from comments.models import Comment
from ckeditor_uploader.fields import RichTextUploadingField


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft = False).filter(publish__lte = timezone.now())

    def all(self, *args, **kwargs):
        return super(PostManager, self).all()


class ContactAdmin(models.Model):
    name    = models.CharField( max_length=120 )
    emailid = models.EmailField(max_length=254)
    subject = models.CharField( max_length=120 )
    message = RichTextUploadingField()

    def __str__(self):
        return self.name

class BlogRequest(models.Model):
    author      = models.CharField(max_length = 120)
    userRequest = models.CharField(max_length = 150)
    created_on  = models.DateTimeField(auto_now=False, auto_now_add=True)
    
    def __str__(self):
        return self.author

class Post(models.Model):
    title           = models.CharField( max_length=120 )
    content         = RichTextUploadingField()
    slug            = models.SlugField(unique = True)
    image           = CloudinaryField('image', null = True, blank = True)
    image_caption   = models.CharField(max_length=100, blank=True, null = True)
    updated_on      = models.DateTimeField(auto_now=True, auto_now_add=False)
    created_on      = models.DateTimeField(auto_now=False, auto_now_add=True)
    author          = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.DO_NOTHING)
    tags            = models.CharField(max_length = 120, null = True, blank = True)
    category        = models.CharField(max_length = 120, null = True, blank = True)
    likes           = models.IntegerField(default=0)
    #dislikes       = models.IntegerField(default=0)
    draft           = models.BooleanField(default=0)
    publish         = models.DateField(auto_now=False, auto_now_add=False)

    objects         = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post-detail", kwargs={"slug": self.slug})
    
    def get_update_url(self):
        return reverse("update-detail", kwargs={"slug": self.slug})
    
    @property
    def comments(self):
        instance = self
        qs       = Comment.objects.filter_by_instance(instance)
        return qs
    
    @property
    def commentsCount(self):
        instance    = self
        ccount      = Comment.objects.filter_by_instance(instance).count()
        return ccount

    @property
    def get_content_type(self):
        instance        = self
        content_type    = ContentType.objects.get_for_model(instance.__class__)
        return content_type

    @property
    def viewscount(self):
        instance    = self
        viewCount   = no_of_views.objects.get(post = instance).views
        return viewCount

class no_of_views(models.Model):
    post       = models.ForeignKey(Post, on_delete=models.CASCADE)
    views      = models.IntegerField(default=0)
    updated    = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.post.title

class UserPrefer(models.Model):
    user    = models.ForeignKey(settings.AUTH_USER_MODEL, default=1,on_delete=models.DO_NOTHING)
    Post    = models.ForeignKey(Post, on_delete=models.CASCADE)
    value   = models.IntegerField()
    date    = models.DateTimeField(auto_now=True, auto_now_add = False)

    def __str__(self):
        return str(self.user) + ':' + str(self.post) +':' + str(self.value)
    

def pre_save_slugify(sender, instance, *args, **kwargs):
    titleslug = slugify(instance.title)
    instance.slug = titleslug +  '-' + strftime("%Y%m%d-%H%M%S", gmtime())

pre_save.connect(pre_save_slugify, sender = Post)

blog/post/forms.py
from django import forms
from .models import Post, ContactAdmin, BlogRequest
from cloudinary.forms import CloudinaryFileField

class contactAdminForm(forms.ModelForm):
    class Meta:
        model = ContactAdmin
        fields = ['name', 'emailid', 'subject', 'message']

class blogRequestForm(forms.ModelForm):
    class Meta:
        model = BlogRequest
        fields = ['author', 'userRequest']


class create_new_post(forms.ModelForm):
    category = forms.CharField()
    title = forms.CharField()
    image = CloudinaryFileField(
        options = {
            'crop': 'scale',
            'width': 500,
            'height': 500,
            'folder': 'blog-images',
        },
        required=False,
    )
    image_caption = forms.CharField(required=False,)
    tags = forms.CharField(widget = forms.TextInput(attrs={
            'data-role' : "tagsinput",
             'class' : "form-control bootstrap-tagsinput",
             'id' : "tags-multiple",
            },
            ),
            required=False,
    )
    publish = forms.DateField(widget = forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = ['category', 'title', 'content', 'image', 'image_caption', 'tags', 'draft', 'publish']

blog/post/views.py
from django.http import HttpResponse, request, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, UserPrefer, no_of_views, ContactAdmin, BlogRequest
from .forms import create_new_post, contactAdminForm, blogRequestForm
from django.utils.text import slugify
from django.conf import settings
import datetime
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView
from django.contrib import messages
from urllib.parse import quote_plus
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.http.response import Http404
from django.utils import timezone
from comments.models import Comment
from comments.forms import CommentForm
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from users.models import UserProfile
# class editBlog(UpdateView):
#     model = Post
#     fields = ['title', 'content', 'image', 'image_caption', 'tags']
#     template_name_suffix = '_update_form'


def handler404(request, exception = None):
    return render(request, 'errors/404.html', status=404)
def handler500(request):
    return render(request, 'errors/500.html', status=500)

@login_required
def create_post(request):
    if not (request.user.is_staff or request.user.is_superuser or request.user.groups.filter(name='BlogWriters').exists()):
        raise Http404
    form = create_new_post()
    if request.method == "POST":
        
        form = create_new_post(request.POST, request.FILES or None)
        if form.is_valid():
            form.cleaned_data['author'] = request.user
            a = Post.objects.create(**form.cleaned_data)
            no_of_views.objects.create(post = a, views = 0)
    context = {
        "form" : form
    }
    return render(request, "post/new_post.html", context)

def blogRequest(request, slug):
    #Blog Request
    rform = blogRequestForm(request.POST or None)
    if 'blog-request' in request.POST:
        if rform.is_valid():
            a = BlogRequest.objects.create(**rform.cleaned_data)
    return redirect('post-detail', slug = slug)

def contactAdmin(request):
    form = contactAdminForm()
    if request.method == "POST":
        form = contactAdminForm(request.POST)
        if form.is_valid():
            a = ContactAdmin.objects.create(**form.cleaned_data)
    context = {
        "form" : form,
        "page" : "Contact Us",
    }
    return render(request, "post/contact.html", context)

def aboutUs(request):
    context  = {
        "page" : "About Us",
    }
    return render(request, "post/about.html", context)

def view_post(request, slug):
    instance = get_object_or_404(Post, slug = slug)
    if instance.draft or instance.publish > timezone.now().date():
        if request.user is not instance.author:
            if not request.user.is_superuser:
                raise Http404
    categories = Post.objects.values('category').distinct()
    tags = Post.objects.values('tags').distinct()
    recent = Post.objects.all().order_by('-updated_on')[:3]
    category_list = []
    for i in categories:
        category_list.append(i['category'])
    tag_list = []
    for i in tags:
        a = (i['tags']).split(',')
        for j in a:
            tag_list.append(j)
    a = (instance.tags).split(',')
    query = no_of_views.objects.get(post = instance)
    if not instance.draft:
        query.views += 1
        query.save()

    
    #Comments
    comments = Comment.objects.filter_by_instance(instance)
    commentscount = comments.count()
    initial_data = {
        "content_type" : instance.get_content_type,
        "object_id" : instance.id,
    }
    form = CommentForm(request.POST or None, initial = initial_data)
    if form.is_valid():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model = c_type)
        obj_id = form.cleaned_data.get("object_id")
        content_data = form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = int(request.POST.get('parent_id'))
        except:
            parent_id = None
        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists():
                parent_obj = parent_qs.first()

        new_comment, created = Comment.objects.get_or_create(
            user = request.user,
            content_type = content_type,
            object_id = obj_id,
            content = content_data,
            parent = parent_obj,
        )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
    
    context = {
        "instance" : instance,
        "categ" : category_list,
        "tags" : list(set(tag_list)),
        "recent" : recent,
        'a' : a,
        'views' : query.views,
        "comments" : comments,
        "commentform" : form,
        "commentscount" : commentscount,
        "page" : "View Post",
    }
    return render(request, "post/detail_post.html", context)


def enlist_post(request):
    categories = Post.objects.values('category').distinct()
    tags = Post.objects.values('tags').distinct()
    recent = Post.objects.all().order_by('-updated_on')[:3]
    category_list = []
    for i in categories:
        category_list.append(i['category'])
    tag_list = []
    for i in tags:
        a = (i['tags']).split(',')
        for j in a:
            tag_list.append(j)
        
    cat = request.GET.get('cat')
    tag = request.GET.get('tag')
    searchq = request.GET.get('search')
    if cat:
        queryset = Post.objects.all().filter(category = cat).order_by('-created_on')
    elif tag:
        queryset = Post.objects.all().filter(tags__contains = tag).order_by('-created_on')
    elif searchq:
        queryset = Post.objects.all().filter(Q(content__icontains = searchq) | Q(title__icontains = searchq)).order_by('-created_on')
    else:
        queryset = Post.objects.all().order_by('-created_on')

    page = request.GET.get('page', 1)
    paginator = Paginator(queryset, 16)
    try:
        numbers = paginator.page(page)
    except PageNotAnInteger:
        numbers = paginator.page(1)
    except EmptyPage:
        numbers = paginator.page(paginator.num_pages)


    context = {
        "posts" : queryset,
        "categ" : category_list,
        "tags" : list(set(tag_list)),
        "recent" : recent,
        'queryset': numbers,
        "page" : "All Posts",
    }
    return render(request, 'post/posts_list.html', context)

def home(request):
    
    
    queryset1 = Post.objects.all().order_by('-updated_on')[:10]
    queryset2 = Post.objects.all().order_by('-created_on')[:10]
    categories = Post.objects.values('category').distinct()
    tags = Post.objects.values('tags').distinct()
    recent = Post.objects.all().order_by('-updated_on')[:3]
    category_list = []
    for i in categories:
        category_list.append(i['category'])
    tag_list = []
    for i in tags:
        a = (i['tags']).split(',')
        for j in a:
            tag_list.append(j)
        
    context = {
        "updatedposts" : queryset1,
        "newposts" : queryset2,
        "categ" : category_list,
        "tags" : list(set(tag_list)),
        "recent" : recent,
        "page" : "Home",
    }
    return render(request, 'post/index.html', context)

# def register(request):
#     return render(request, 'post/login.html')

@login_required
def delete_post(request, slug = None):
    instance = get_object_or_404(Post, slug = slug)
    if not (instance.author == request.user or request.user.is_superuser):
        raise 404
    instance.delete()
    messages.success(request, "Successfully Deleted")
    return redirect('post-list')

@login_required
def update_post(request, slug = None):
    instance = get_object_or_404(Post, slug = slug)
    if instance.author.id == request.user.id or request.user.is_superuser:
        
        form = create_new_post(request.POST or None, request.FILES or None, instance = instance)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return redirect('post-list')
        image_url = instance.image
        context = {
            "instance" : instance,
            "form" : form,
            'imgurl' : image_url,
        }
    else:
        raise Http404
    

    return render(request, "post/update_post.html", context)



@login_required
def like(request, id = None):
    q = request.GET.get('q')
    postQuery = get_object_or_404(Post, id = id)
    try:
        query = UserPrefer.objects.filter(Post = postQuery, user = request.user )
        if query.count() == 0:
            UserPrefer.objects.create(Post = postQuery, value = q, user = request.user)
            postQuery.likes += 1
            
        else:
            query.delete()
            postQuery.likes -= 1
        print(query.count())
            
    except UserPrefer.DoesNotExist:
        postQuery.likes += 1
        UserPrefer.objects.create(Post = postQuery, value = q, user = request.user)
        
            

    postQuery.save()
    
    redirect_to = '/view/'+ postQuery.slug

    return HttpResponseRedirect(redirect_to)
    

def authorProfile(request, id = None):
    username = get_object_or_404(User, id = id)
    a = get_object_or_404(UserProfile, user = username)
    if a.profileDetailsVisible != 1:
        raise Http404
    profilePic, coverPic = a.profilePic, a.coverPic
    profile = UserProfile.objects.get(user = username)
    context = {
        'profile' : profile,
        'pp'     : profilePic,
        'cp'     : coverPic,
        "page"   : "Author's Profile",
    }
    return render(request, 'post/authorProfile.html', context)

blog/templates/post/about.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>Curious about ScribeIt</h4>
                <h2>Get acquainted with us here!</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    
    <!-- Banner Ends Here -->


    <section class="about-us">
      <div class="container">
      	
        <div class="row">
          <div class="col-lg-12">
            <img src="{% static 'assets/images/about-us.jpg' %}" alt="">
            <p>
              We've seen and done it all and we unite to start First Site Guide because we believe in the web for everyone. We can help you start a personal or business blog/site, a place to show your hobbies, offer advice to others, or just to share personal stories, pictures, and videos.
            </p><p>
              The web is a great place to be and make new connections from all parts of the world or just your neighborhood. Buy, sell, share your hobby passion, or just educate and entertain. We want you to be a part of it. Our motive is to create a unique platforms for blogholics that will motivate people, empower them to let their creative mind speak through them
            </p><p>
              Once we get you there, don't forget to check back in for technical, advice, social media, and marketing articles to help you navigate the digital highway. Bookmark us, like us, follow us and we'll be your digital information source. If you have any questions feel free to contact us at any time.
            </p>
          </div>
        </div>
        
      
        
        <div class="row">
          <div class="col-lg-12">
            <ul class="social-icons">
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-behance"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
        
        
      </div>
    </section>

    
    
      
    {% endblock content %}
      

blog/templates/post/detail_post.html
{% extends "../base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% load has_group %}
{% block head %}

{{ instance.author }}'s Post 

{% endblock head %}


{% block head-extra %}
    {{ commentform.media }}
    <style>
      .wmd-preview{
        display: none !important;
    }
    </style>
{% endblock head-extra %}

{% block content %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>{{ instance.title }}</h4>
                <h2> Written By {{ instnce.author }} </h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    
    <!-- Banner Ends Here -->

    <section class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="main-content">
              {% if request.user|has_group:"BlogWriters" %} 
              <div class="row">
                <div class="col-lg-8">
                  <span>You are a Blog Writer</span>
                  <h4>Manage your Posts and Profile</h4>
                </div>
                <div class="col-lg-4">
                  <div class="main-button">
                    <a href="{% url 'users:admin-home' %}" target="_parent">Click Here!</a>
                  </div>
                </div>
              </div>
              {% else %}
              <div class="row">
                <div class="col-lg-8">
                  <span>Do you have a good story to tell?</span>
                  <h4>Be a blogger, Write your thoughts & share them here!!</h4>
                </div>
                <div class="col-lg-4">
                  <div class="main-button">
                    <a href="{% url 'users:make-bloggers' %}" target="_parent">Click Here!</a>
                  </div>
                </div>
              </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </section>


    <section class="blog-posts grid-system">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              
              <div class="row">
                <div class="col-lg-12">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      {% if instance.image %}
                      <img src="{{ instance.image.url }}" alt="an image" class="img-responsive" >
                      {% else %}
                      <img src="{% static 'assets/images/banner-item-04.jpg'%}" alt="">
                      {% endif %}
                    </div>
                    <div class="down-content">
                      <span>Category</span>
                      <a href="{% url "post-detail" slug=instance.slug %}"><h4>
                        {% if instance.draft %} 
                          <h4 style="color: red;" > Draft Post </h4>
                        {% endif %}
                        {{ instance.title }}</h4></a>
                      <ul class="post-info">
                        <li><a href="{% url "author-profile" id=instance.author.id %}"> {{ instance.author }} </a></li>
                        <li><a href="#"> {{ instance.created_on }} </a></li>
                        <li><a href="#"> {{ commentscount }} Comments</a></li>
                      </ul>
                     
                        {{ instance.content|safe }}
                      
                      <div class="post-options">
                        <div class="row">
                          <div class="col-4">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              {% if a %}
                              {% for i in a %}
                                <li><a href="{% url 'post-list' %}?tag={{ i }}"> {{ i|upper }} </a></li>
                              {% endfor %}
                              {% else %}
                              <li><a href="#"> GENERAL </a></li>
                              {% endif %}
                            </ul>
                          </div>
                          <div class="col-4">
                            <ul class="post-likes">
                              <li>
                                <i class="fa fa-eye"></i> {{ views }} |
                                <a href="{% url 'post-like' id=instance.id %}?q=1"> <i class="fa fa-thumbs-up"></i></a>  {{ instance.likes }} 
                                <!-- <a href="{% url 'post-like' id=instance.id %}?q=2"> <i class="fa fa-thumbs-down"></i>  </a>   {{ instance.dislikes }} -->
                              </li>
                            </ul>
                          </div>
                          <div class="col-4">
                            <ul class="post-share">
                              <li><i class="fa fa-share-alt"></i></li>
                              <li><a href="https://www.facebook.com/sharer/sharer.php?u={{ requests.build_absolute_uri }}"">Facebook</a>,</li>
          
                              <li><a href="https://twitter.com/home?status={{ requests.build_absolute_uri }}"> Twitter</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item comments">
                    <div class="sidebar-heading">
                      <h2> {{ commentscount }}  comments</h2>
                    </div>
                    
                    <div class="content">
                      
                      <ul>
                        {% for comment in comments %}
                        <li>
                          <div class="author-thumb">
                            <img src="" alt="">
                          </div>
                          <div class="right-content">
                            <h4> {{ comment.user }} <span> {{ comment.timestamp|timesince }} ago </span>
                              <small>
                                | {% if comment.children.count > 0 %}
                            {{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} 
                           {% endif %}
                           |
                           <a href="javascript:;" onClick="func(this);"  class="reply-button">Reply</a>
                           
                              </small>
                            </h4>
                            <p>
                              {{ comment.content|safe }}
                            </p>
                          </div>
                          
                            
                        </li>
                        
                              <div class="content comment-reply" style="display: none;">
                                <form id="comment" method="POST" action = "{% url "post-detail" slug=instance.slug %}" enctype="multipart/form-data"> {% csrf_token %}
                                  
                                  {{ commentform|crispy }}
                                  <div class="col-lg-12">
                                    <input type="hidden" name="parent_id" value="{{ comment.id }}">
                                    {% if user.is_authenticated %}
                                    <fieldset>
                                      <button type="submit" name="comment" id="form-submit" class="main-button">Reply</button>
                                    </fieldset>
                                    {% else %}
                                    <div>
                                      Need to be signed in to reply on comments
                                    </div>
                                    {% endif %}
                                  </div>
                                
                              </form>
                              
                            
                            {% for child in comment.children %}
                              <li class="replied">
                                <div class="author-thumb">
                                  <img src="" alt="">
                                </div>
                                <div class="right-content">
                                  <h4> {{ child.user }} <span> {{ child.timestamp|timesince }} ago </span></h4>
                                  <p> {{ child.content }} </p>
                                </div>
                              </li>
                              {% endfor %}
                            </div>
                        {% endfor %}
                        
                      </ul>
                    </div>
                    
                  </div>
                </div>
                <div class="col-lg-12">
                  {% if user.is_authenticated %}
                  <div class="sidebar-item submit-comment">
                    <div class="sidebar-heading">
                      <h2>Your comment</h2>
                    </div>
                    <div class="content">
                        <form id="comment" method="POST" action = "{% url "post-detail" slug=instance.slug %}" enctype="multipart/form-data"> {% csrf_token %}
                          
                          {{ commentform|crispy }}
                          <div class="col-lg-12">
                            <fieldset>
                              <button type="submit" id="form-submit" name="comment" class="main-button">Submit</button>
                            </fieldset>
                          </div>
                        
                      </form>
                    </div>
                  </div>
                  {% else %}
                  <div>
                    <h3> In order to comment, you need to be signed in </h3>
                  </div>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            {% include '../sidebar.html' %}
            <p>
              Do you want to request author of this post to write new content based on your interest?</br>
              Tell what you want to read next here!
            </p>
            <form class="input-group" method="POST" action="{% url "blog-request" slug=instance.slug %}" id="blog-request"> {% csrf_token %}
              
              <input type="hidden" name="author" value="{{ instance.author }}">
              <div class="input-group mb-3">
              <input class="blog-request-input form-control" type="text" name="userRequest" id="userRequest">
              <div class="input-group-append">
              <button type="submit" name="blog-request" id="formsubmit" class="blog-request-button form-control">Request</button>
              </div>
            </div>
            
            </form>
          </div>
        </div>
      </div>
    </section>

    
    {% endblock content %}