blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users import views


handler404 = "post.views.handler404"
handler500 = "post.views.handler500"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include("users.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include("post.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'users'


urlpatterns = [
    path('register/', views.register,name='register' ),
    path('user_login/', views.user_login,name='user_login' ),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'), 
    path('managePosts/', views.managePosts, name='manage-posts'),
    path('logout/', views.logmeout, name='log-out'),
    path('beblogger/', views.makeBloggers, name='make-bloggers'),
    path('profile/', views.userProfile, name='user-profile'),
    path('profile-edit/', views.edit_profile, name='user-profile-edit'),
    path('', views.adminHome, name='admin-home'),
    
]

blog/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from cloudinary.models import CloudinaryField
from ckeditor.fields import RichTextField

class UserProfileManager(models.Manager):
    pass

class UserProfile(models.Model):
    #gender choice
    GENDER_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    ]
    #user = models.OneToOneField(User)
    user                     = models.OneToOneField(User, on_delete=models.CASCADE)
    description              = models.TextField(default='', null = True, blank = True)
    address                  = models.TextField(default='', null = True, blank = True)
    website                  = models.URLField(default='', null = True, blank = True)
    gender                   = models.CharField(max_length = 20, default = 'Male')
    mobileNumber             = models.IntegerField(default=0, null = True, blank = True)
    profilePic               = CloudinaryField('image', null = True, blank = True)
    coverPic                 = CloudinaryField('image', null = True, blank = True)
    #privacy
    contactDetailsVisible    = models.IntegerField(default = 0, null = True, blank = True)
    profileDetailsVisible    = models.IntegerField(default = 1, null = True, blank = True)
    #Fav
    fav_music                = models.CharField(max_length = 120, null = True, blank = True)
    fav_books                = models.CharField(max_length = 120, null = True, blank = True)
    fav_movie                = models.CharField(max_length = 120, null = True, blank = True)
    skills                   = models.CharField(max_length = 120, null = True, blank = True)
    interest                 = models.CharField(max_length = 120, null = True, blank = True)
    facebook_url             = models.URLField(max_length=200, null = True, blank = True)
    linkedin_url             = models.URLField(max_length=200, null = True, blank = True)
    twitter_url              = models.URLField(max_length=200, null = True, blank = True)
    instagram_url            = models.URLField(max_length=200, null = True, blank = True)
    


    def __str__(self):
        return self.user.username


def create_profile(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        user_profile = UserProfile(user=user)
        user_profile.save()
post_save.connect(create_profile, sender=User)

blog/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm
from ckeditor.widgets import CKEditorWidget
from cloudinary.forms import CloudinaryFileField

from .models import UserProfile


class UserForm(forms.ModelForm):
    username = forms.CharField(widget = forms.TextInput(attrs={
             'class' : "input-field",
             'label' : "Username",
            },
            ),
            required=True,
    )
    email = forms.EmailField( required = True),
    password = forms.CharField(widget=forms.PasswordInput(attrs={
             'class' : "input-field",
             'label' : "Password",
            },
            ),
            required=True,
            
    )
    class Meta():
        model = User
        fields = ('username','password','email')


class EditProfileForm(ModelForm):
        first_name = forms.CharField(widget = forms.TextInput(attrs={
             'class' : "validate",
             'label' : "First Name",
                'id' : "first-name"
            },
            ),
        )
        last_name = forms.CharField(widget = forms.TextInput(attrs={
             'class' : "validate",
             'label' : "Last Name",
                'id' : "last-name"
            },
            ),
        )
        email = forms.EmailField( widget = forms.EmailInput(attrs={
                'class' : "validate",
                'label' : "Email ID",
                'id' : "email"
        })),
        class Meta:
            model  = User
            fields = (
                    'email',
                    'first_name',
                    'last_name'
                    )
class ProfileForm(ModelForm):
        
        
        

        profilePic = CloudinaryFileField(
        options = {
            'crop': 'scale',
            'width': 500,
            'height': 500,
            'folder': 'blog-images',
        },
        required=False,
    )
        
        description = forms.CharField(widget=forms.Textarea(
                attrs = {
                        'id' : 'description',
                }
        ), required = False)
        address = forms.CharField(widget=forms.Textarea(
                attrs = {
                        'id' : 'address',
                        'data-length' : '60',
                }
        ), required = False)
        class Meta:
                model  = UserProfile
                fields = (
                'description', 'gender',
                'address',
                'mobileNumber', 'website', 'profilePic', 'coverPic',
                'contactDetailsVisible', 'profileDetailsVisible',
                'fav_music', 'fav_books', 'fav_movie', 
                'skills', 'interest',
                'facebook_url', 'linkedin_url', 'twitter_url', 'instagram_url',
                ) 

blog/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.utils.encoding import force_bytes, force_text  
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode  
from django.template.loader import render_to_string
from django.contrib.auth.models import User, Group 
from users.forms import UserForm, EditProfileForm, ProfileForm
from .tokens import account_activation_token  
from django.core.mail import EmailMessage
from  post.models import Post
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import UserProfile


def logmeout(request):
    logout(request)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def managePosts(request):
    username = request.user
    q = Post.objects.filter(author = username)
    context = {
        'posts' : q,
    }
    return render(request, 'users/managePosts.html', context)

def adminHome(request):
    username = request.user
    if username.is_superuser:
        query = Post.objects.all()
    else:
        query = Post.objects.filter(author = username)
    
    page = request.GET.get('page', 1)
    paginator = Paginator(query, 16)
    try:
        numbers = paginator.page(page)
    except PageNotAnInteger:
        numbers = paginator.page(1)
    except EmptyPage:
        numbers = paginator.page(paginator.num_pages)
    context = {
        'posts' : numbers,
    }

    return render(request, 'users/adminHome.html', context)

def register(request): 
    if request.method == 'POST':
        form = UserForm(request.POST)  
        # print(form.errors.as_data())  
        if form.is_valid():  
            user = form.save(commit=False)  
            user.is_active = False  
            pwd = form.cleaned_data['password']
            user.set_password(pwd)
            user.save()  
            current_site = get_current_site(request)  
            mail_subject = 'Activate your account.'  
            message = render_to_string('users/activatemail.html', {  
                'user': user,  
                'domain': current_site.domain,  
                'uid': urlsafe_base64_encode(force_bytes(user.id)),  
                'token': account_activation_token.make_token(user),  
            })  
            to_email = form.cleaned_data.get('email')  
            email = EmailMessage(  
                mail_subject, message, to=[to_email]  
            )  
            email.send()  
            return HttpResponse('Please confirm your email address to complete the registration')  
    else:  
        form = UserForm() 
    return render(request, 'users/registration.html', {'user_form': form})

def activate(request, uidb64, token):  
    try:  
        uid = force_text(urlsafe_base64_decode(uidb64))  
        user = User.objects.get(id=uid)  
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):  
        user = None  
    if user is not None and account_activation_token.check_token(user, token):  
        user.is_active = True  
        user.save()  
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')  
    else:  
        return HttpResponse('Activation link is invalid!')

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect('../../')
            else:
                return HttpResponse("Your account is inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'users/login.html', {})

@login_required
def makeBloggers(request):
    name = request.user
    g = Group.objects.get(name='BlogWriters')
    g.user_set.add(name)
    return redirect('posts-home')
    
def userProfile(request):
    print(request.user.id)
    a = get_object_or_404(UserProfile, user = request.user)
    profilePic, coverPic = a.profilePic, a.coverPic
    profile = UserProfile.objects.get(user = request.user)
    context = {
        'profile' : profile,
        'pp'     : profilePic,
        'cp'     : coverPic,
    }
    return render(request, 'users/profile.html', context)


@login_required
def edit_profile(request):
    if request.user.userprofile is None:
        user_profile = UserProfile(user=request.user)
        user_profile.save
    if request.method == 'POST':
        form = EditProfileForm(request.POST, request.FILES or None, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES or None, instance=request.user.userprofile)  # request.FILES is show the selected image or file

        if form.is_valid() and profile_form.is_valid():
            contactPrivacy = request.POST.get('contactPrivacy')
            profilePrivacy = request.POST.get('profilePrivacy')
            gender         = request.POST.get('gender')
            user_form = form.save()
            custom_form = profile_form.save(False)
            custom_form.user = user_form
            custom_form.contactDetailsVisible = contactPrivacy
            custom_form.profileDetailsVisible = profilePrivacy
            custom_form.gender                = gender
            custom_form.save()
            return redirect('users:user-profile')
    a = get_object_or_404(UserProfile, user = request.user)
    profilePic, coverPic = a.profilePic, a.coverPic
    form = EditProfileForm(instance=request.user)
    profile_form = ProfileForm(instance=request.user.userprofile)
    # args.update(csrf(request))
    context = {
        'form'   : profile_form,
        'myform' : form,
        'pp'     : profilePic,
        'cp'     : coverPic,
        'a'      : a,
    }
    return render(request, 'users/editprofile.html', context)

blog/templates/users/activatemail.html
{% autoescape off %}  
Hi {{ user.username }},  
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}  
If you think, it's not you, then just ignore this email.  
{% endautoescape %}

blog/templates/users/adminHome.html
{% extends 'users/base.html' %}
{% load static %}

{% block extrahead %}
    
   
{% endblock extrahead %}
    

{% block content %}

    
    <!-- Cards -->
<section class="fcard infinite-container" style="background: #ffd180;">
	
    <div class="row" style="padding-top: 30px; padding-left: 25%; padding-right: 25%;">
        {% for post in posts %}
      <div class="col-lg-6" >
        <div class="card infinite-item" style="background: #e65100; width:100%;">
          <div class="card-image">
            <img style="height: 400px;" src="
            {% if post.image.url %}
                          {{ post.image.url }}
                          {% else %}
                          {% static 'assets/images/no-img.png' %}
                          {% endif %}
                          ">
            <span class="card-title">{{ post.title }}</span>
          </div>
          <div class="card-content" style="background: #ffd180; height:220px;">
            <p>
                {{ post.content|safe|truncatewords:25 }} 
                <a href="{% url 'post-detail' slug=post.slug %}">Read more</a>
            </p>
          </div>
          <div class="container">
              <div class="row" style="background: #e65100;">
                  <div class="col s12 l4 center" style="padding-top: 10px;">
                      <span style="font-size: 30px;">{{ post.likes }}</span>
                      <i class="small material-icons">thumb_up</i>
                  </div>
                  <div class="col s12 l4 center" style="padding-top: 10px;">
                      <span style="font-size: 30px;">{{ post.viewscount }}</span>
                       <i class="small material-icons">visibility</i>
                   </div>
                  <div class="col s12 l4 center" style="padding-top: 10px;"> 
                      <span style="font-size: 30px;"> {{ post.commentsCount }} </span>
                       <i class="small material-icons">comment</i>
                   </div>
              </div>
              
          </div>
        </div>
      </div>
      {% endfor %}
      {% if numbers.has_next %}
      <a class="infinite-more-link" href="?page={{ numbers.next_page_number }}">More</a>
    {% endif %}

    <div class="loading" style="display: none;">
      Loading...
    </div>
    </div>
   

  </section>

{% endblock content %}
    

blog/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Blogging Website</title>
  <!-- google font -->
  <link href="https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap" rel="stylesheet"> 
  <!-- M Icons -->
   <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
   <!-- Acutal M -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
   <!-- Icons -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
   <!-- custom css -->
   <link rel="stylesheet" href="{% static 'assets/css/adminDashboard.css'%}">

   
   {% block extrahead %}
     
   {% endblock extrahead %}
     
</head>
<body>
<!-- NavBar -->
<section class="fnavbar">
   <nav class="nav-fixed">
       <div class="nav-wrapper">
         <a href="#" class="brand-logo" style="margin-left: 50px">ScribeIt!</a>
         <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            {% if request.user.is_authenticated %}
              <li><a href="{% url 'users:admin-home' %}"><i class="material-icons left">home</i>Home</a></li>
              <li><a href="{% url 'create-post' %}"><i class="material-icons left">playlist_add</i>Create New Post</a></li>
              <li><a href="{% url 'users:manage-posts' %}"><i class="material-icons left">burst_mode</i>Manage Posts</a></li>
              <li><a href="{% url 'posts-home' %}"><i class="material-icons left">dvr</i>Visit Site</a></li>
              <li><a href="{% url 'users:user-profile' %}"><i class="material-icons left">person</i>My Profile</a></li>
              <li><a href="{% url 'users:log-out' %}"><i class="material-icons left">exit_to_app</i>Log Out</a></li>
            {% else %}
              <li><a href="{% url 'users:admin-home' %}"><i class="material-icons left">home</i>Home</a></li>
              <!-- <li><a href="#"><i class="material-icons left">burst_mode</i>Manage Posts</a></li> -->
              <li><a href="{% url 'posts-home' %}"><i class="material-icons left">dvr</i>Visit Main Site</a></li>
              <li><a href="{% url 'users:user_login' %}"><i class="material-icons left">person</i>Log In</a></li>
              <li><a href="{% url 'users:register' %}"><i class="material-icons left">exit_to_app</i>Register</a></li>
            {% endif %}
          </ul>
        </div>

      </nav>

      <ul class="sidenav" id="mobile-demo">
              {% if request.user.is_authenticated %}
              <li><a href="{% url 'users:admin-home' %}"><i class="material-icons left">home</i>Home</a></li>
              <li><a href="{% url 'create-post' %}"><i class="material-icons left">playlist_add</i>Create New Post</a></li>
              <li><a href="{% url 'users:manage-posts' %}"><i class="material-icons left">burst_mode</i>Manage Posts</a></li>
              <li><a href="{% url 'posts-home' %}"><i class="material-icons left">dvr</i>Visit Site</a></li>
              <li><a href="{% url 'users:user-profile' %}"><i class="material-icons left">person</i>My Profile</a></li>
              <li><a href="{% url 'users:log-out' %}"><i class="material-icons left">exit_to_app</i>Log Out</a></li>
            {% else %}
              <!-- <li><a href="{% url 'users:admin-home' %}"><i class="material-icons left">home</i>Home</a></li> -->
              <!-- <li><a href="#"><i class="material-icons left">burst_mode</i>Manage Posts</a></li> -->
              <li><a href="{% url 'posts-home' %}"><i class="material-icons left">dvr</i>Visit Main Site</a></li>
              <li><a href="{% url 'users:user_login' %}"><i class="material-icons left">person</i>Log In</a></li>
              <li><a href="{% url 'users:register' %}"><i class="material-icons left">exit_to_app</i>Register</a></li>
            {% endif %}
      </ul>
</section>

<!-- Slider -->
<section class="fslider">
  <div class="slider" style="background: #ffd180;">
    <ul class="slides">
      <li>
        <img src="{% static 'assets/images/bl1.jpg' %}" alt="image one">
      </li>
      <li>
        <img src="{% static 'assets/images/bl5.jpg' %}" alt="image one">
      </li>
      <li>
        <img src="{% static 'assets/images/bl6.jpg' %}" alt="image one">
      </li>
      <li>
        <img src="{% static 'assets/images/bl7.jpg' %}" alt="image one">
      </li>
    </ul>
  </div>
</section>

{% block content %}
  
{% endblock content %}



<!-- parallex -->
<section class="fparallex">
  <div class="parallax-container" >
      <div class="parallax"><img src="{% static 'assets/images/px.jpg' %}"></div>
    </div>
</section>

<!-- AboutUs -->
<section class="fabout">
	<div class="section center" style="background: #ffd180;" >
		<div class="row container">
		  <h2 class="header">About Us</h2>
		  <p class="grey-text text-darken-3">
        We've seen and done it all and we unite to start First Site Guide because we believe in the web for everyone. We can help you start a personal or business blog/site, a place to show your hobbies, offer advice to others, or just to share personal stories, pictures, and videos.
      </p><p class="grey-text text-darken-3">
        The web is a great place to be and make new connections from all parts of the world or just your neighborhood. Buy, sell, share your hobby passion, or just educate and entertain. We want you to be a part of it. Our motive is to create a unique platforms for blogholics that will motivate people, empower them to let their creative mind speak through them
      </p><p class="grey-text text-darken-3">
        Once we get you there, don't forget to check back in for technical, advice, social media, and marketing articles to help you navigate the digital highway. Bookmark us, like us, follow us and we'll be your digital information source. If you have any questions feel free to contact us at any time.
      </p>
		   <a href="#" class="btn waves-effect waves-light" style="background: #e65100 !important;">Read More</a>
	    </div>
	</div>
</section>






<!-- footer -->
<section class="ffooter">
  <footer class="footer-one">
    <div class="container">
      <div class ="row center">


        
        <div class="col s12 l6">
          <div class="container white-text">

          <div class ="row">
              <h4>Contact Us</h4>
          </div>

          <div class ="row">

            <section class="fcontact">
                           <div class="row" style="padding-right: 10px padding-left:10px">
                            <div class="col s12 l4 center" style="padding:10px">
                              <i class="fa fa-address-card small"></i>
                              <h6 class="header">Shanti Nagar Delhi- 441502 </h6>
                            </div>
                            <div class="col s12 l4 center" style="padding: 10px">
                              <i class="fa fa-phone-square small"></i>
                                <h6 class="header">+918788303454</h6>
                  </div>
             
                     </div>
                 </section>
            </div>    
            </div>
            </div>

        <div class="col s12 l6">
          <div class="container white-text">

          <div class ="row">
              <h4>Social Media</h4>
          </div>

          <div class ="row">

            <section class="fmedia">
                           <div class="row" style="padding-right: 10px padding-left:10px">
                            <div class="col s12 l4 center" style="padding: 10px">
                              <!-- <i class="small material-icons">facebook-square</i> -->
                              <i class="fa fa-facebook-square small"></i>
                              <h6 class="header">Facebook</h6>
                            </div>
                            <div class="col s12 l4 center" style="padding: 10px">
                              <i class="fa fa-instagram small"></i>
                                <h6 class="header">Instagram</h6>
                  </div>
                  <div class="col s12 l4 center" style="padding: 10px">
                    <i class="fa fa-twitter-square small"></i>
                    <h6 class="header">Twitter</h6>
                  </div>
                     </div>
                 </section>
            </div>    
            </div>
            </div>



      </div>
      </div>


        

          
    
    <div class="row footer-two">
      <div class="col s12 l6 center">
        <p class="white-text">&copy; ScribeIt</p>
      </div>
      <div class="col s12 l6 center">
        <p class="white-text">Designed by Web Dev Team</p>
      </div>
    </div>

  </footer>
</section>


</body>

<!-- JQuery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>

<!-- M Script -->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

 <!-- custom js -->

 <script src="{% static 'assets/js/loader.js' %}"></script>

 

</html>

blog/templates/users/index.html
{% extends "users/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Djungle !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

blog/templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}
{% load socialaccount %}




{% block content %}
	
	<!-- Form -->
<section class="form" style="background: #ffd180;">
	
	<div class="row">
	  <div class="col s12 l4 " style="overflow: hidden;">
		  <img src="{% static 'assets/images/pa.png' %}" alt="image one" style="height: 500px; width: 450px;">

	  </div>	

	  <div class="col s12 l4">
		<form class="input-group" method="POST" action="{% url 'users:user_login' %}" id="login"> {% csrf_token %}
		   <h4 class="header center">Login Here</h4>
		   <div class="social-icons" style="padding-top: 20px;">
			<a href="{% provider_login_url 'facebook' %}"> <img src="{% static 'assets/images/fb.png'%}"> </a>
			<a href="{% provider_login_url 'github' %}">  <img src="{% static 'assets/images/github-logo.png'%}"> </a>
			 <a href="{% provider_login_url 'google' %}">  <img src="{% static 'assets/images/goo.png'%}"> </a>
		 </div>
		   <div class="row center"> 
			

			  <div class="input-field col s12">
				<input id="userid" type="text" name="username" class=" validate black-text text-darken-4" required>
				<label for="userid" class="black-text text-darken-4">User Name</label>
			  </div>
			  <div class="input-field col s12">
				<input id="pass" name="password" type="Password" class=" validate black-text text-darken-4">
				<label for="pass" class="black-text text-darken-4">Password</label>
			  </div>

			  <div class="input-field col s12">
				<p>
				   <label>
					<input type="checkbox" class="filled-in" checked="checked" />
					   <span class="black-text text-darken-4">Remember me</span>
				   </label><br>
				   <label><span><a href="#" style="color: #e65100;">Forgot Password</a></span></label>
				</p>
			  </div>


			  <div class="input-field col s12">
				<button class="btn waves-effect waves-light" type="submit" name="action">Login
				   <i class="material-icons right">send</i>
				  </button>
			  </div>


		   </div>
		 </form>
	  </div>

	  <div class="col s12 l4"></div>
	</div>

</section>

{% endblock content %}

blog/templates/users/managePosts.html
{% extends 'users/base.html' %}
{% load static %}


{% block content %}
	<!-- Cards -->
<section class="fcard" style="background: #ffd180;">

	<div class="row" style="padding-left: 50px; padding-right: 50px">
		{% for post in posts %}
		<div class="col s12 m12 l4" style="padding: 50px 50px;">
			 <div class="card" style="background: #ffd180;">
					<div class="card-image waves-effect waves-block waves-light">
                          <img class="activator" src="
                            {% if post.image.url %}
                          {{ post.image.url }}
                          {% else %}
                          {% static 'assets/images/no-img.png' %}
                          {% endif %}
                          ">
				  </div>
					 <div class="card-content">
					  <span class="card-title activator grey-text text-darken-4">{{ post.title }}</span>
				  </div>
				   <div class="row center" style="padding-left: 10px; padding-right: 10px">
						<div class="col s12 l4" style="padding: 5px 5px;"><a href="{% url 'post-detail' slug=post.slug %}" class="waves-effect waves-light btn btn-small" style="background: #e65100 !important;"><i class="tiny material-icons left">remove_red_eye</i>view</a></div>
						<div class="col s12 l4" style="padding: 5px 5px;"><a href="{% url 'edit-post' slug=post.slug %}" class="waves-effect waves-light btn btn-small" style="background: #e65100 !important;"><i class="tiny material-icons left">edit</i>edit</a></div>
						<div class="col s12 l4" style="padding: 5px 5px;"><a href="{% url 'delete-post' slug=post.slug %}" class="waves-effect waves-light btn btn-small" style="background: #e65100 !important;"><i class="tiny material-icons left">delete</i>delete</a></div>
				   </div>
			 </div>
		</div>
		{% endfor %}
	</div>

	</section>


{% endblock content %}

blog/templates/users/registration.html
{% extends 'users/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load socialaccount %}
{{ form.media.js }}


{% block content %}
	
	
<!-- Form -->
<section class="fform" style="background: #ffd180;">
	
	<div class="row">
	  <div class="col s12 l4 " style="overflow: hidden;">
		  <img src="{% static 'assets/images/pa.png' %}" alt="image one" style="height: 500px; width: 450px;">

	  </div>	

	  <div class="col s12 l4">
		<form class="input-group" method="POST" action="{% url 'users:register' %}" id="register">
			{% csrf_token %}
		   <h4 class="header center">Register Here</h4>
		   <div class="social-icons" style="padding-top: 20px;">
			<a href="{% provider_login_url 'facebook' %}"> <img src="{% static 'assets/images/fb.png'%}"> </a>
			<a href="{% provider_login_url 'github' %}">  <img src="{% static 'assets/images/github-logo.png'%}"> </a>
			 <a href="{% provider_login_url 'google' %}">  <img src="{% static 'assets/images/goo.png'%}"> </a>
		 </div>
		   <div class="row center">
			  <div class="input-field col s12">
				<input id="email" name="email" type="email" class="validate black-text text-darken-4">
				<label for="email" class="black-text text-darken-4">Email</label>
			  </div>
			  <div class="input-field col s12">
				<input id="userid" name="username" type="text" class="validate black-text text-darken-4">
				<label for="userid" class="black-text text-darken-4">User Name</label>
			  </div>
			  <div class="input-field col s12">
				<input id="pass" name="password" type="Password" class="validate black-text text-darken-4">
				<label for="pass" class="black-text text-darken-4">Password</label>
			  </div>

			  <div class="input-field col s12">
				<p>
				   <label>
					<input type="checkbox" class="filled-in" checked="checked" required/>
					   <span class="black-text text-darken-4">I agree to the terms & conditions</span>
				   </label>
				</p>
			  </div>

			  <div class="input-field col s12">
				<button class="btn waves-effect waves-light" type="submit" name="action">Submit
				   <i class="material-icons right">send</i>
				  </button>
			  </div>


		   </div>
		 </form>
	  </div>

	  <div class="col s12 l4"></div>
	</div>

</section>



{% endblock content %}
	